language: android

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - mvn package -am -B -V -U
  - android list target
  - bash -c 'cd secure-device-storage/sds-android/ && ./gradlew connectedAndroidTest'
  - bash -c 'cd secure-mobile-push/smp-android-client/ && ./gradlew connectedAndroidTest'
  - bash -c 'cd sms-parser/android-sms-parser/ && ./gradlew connectedAndroidTest'

install:
  - mvn install -DskipTests -Dmaven.javadoc.skip=true -B -V

android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.2
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  sudo: false
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - intel-android-extra-license.+
env:
  global:
  - ADB_INSTALL_TIMEOUT=8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
after_success:
- sh zip-apks.sh

# deploy:
  # provider: releases
  # api_key:
    # secure: R/dS4ZItycLWILoPidUm8lk0SR9ru4GMHpm3N2xdYkp2+7or3mO7Twu18a1SbPkPAaWT/mqDheEYzDYpufb3cLCG0rR368D/qqXg1/OhZ0Cwna0f1JglCQexi0WXFZeWUHP6A/iki1t+ahPtRMPxGWWUm1ZMyAhjxY2Abi/xcpyuLH6zjk5bGjtnaI8RAjfzlC4lExEBWX82nnsYJmQrt3V+5fUIu/IQGypSsyW2fghc5DJXiweRjIgnGizFqG4KweXvnZV1fcy79S2YAcVHirROZlDj5+LvRRNZKwwv18ZJm/IKH3cccAxIADTNp8tWlOAoRT8zplLC4mdkD+JSLOK7E+yPO7nKZ8Mtw7n+kQL2/jQixhh5GJfvYXw14vBr6PySRQt+Dq4zIUHMB+lVsi+cpqAlz0T9KbUcoVG/+8B6b955yb516fVe68+k/sM2zTRUZU3LrInB1cMirBq2yifRGeQzDVA18wF8rksCH5fyiSIElAC/URDCGrGdlpzIONrf3YnyRKh4vjQIz35uELd28WZAnvLExvcvGhD9teVWNZiiPVVBDgDFVZ5cEKdZzB0N26gnw+s8C/vsqE0YlqVqilCxXusGt71eKyIc79uB3rbjsfngWXP6yQasMvFJX83lQ3NTqadxSxdHyPb1ewTZP+hsKiBH+Sy/MSTYX78=
  # file: generated-apks.zip
  # skip_cleanup: true
  # file_glob: true
  # overwrite: true
  # on:
    # repo: adorsys/secure-key-storage