language: android

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - mvn package -am -B -V -U
  - android list target
  - bash -c 'cd secure-device-storage/sds-android/ && ./gradlew connectedAndroidTest'
  - bash -c 'cd secure-mobile-push/smp-android-client/ && ./gradlew connectedAndroidTest'
  - bash -c 'cd sms-parser/android-sms-parser/ && ./gradlew connectedAndroidTest'

install:
  - mvn install -DskipTests -Dmaven.javadoc.skip=true -B -V

android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.2
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services
  sudo: false
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - intel-android-extra-license.+
env:
  global:
  - ADB_INSTALL_TIMEOUT=8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
after_success:
- sh zip-apks.sh
- sh set-tags.sh

deploy:
  provider: releases
  api_key:
    secure: VynSroJaxos4SOe1ObOxBQL5IFfWoj3QYVa/N2TCM/06uU9wy2/TherYp/H4JUyisxiVm92g2bAf++oM6i3cY+++peGvYTtQqYuT04uc2eFJ4IkCE7jiviuFIEWd1HLDNPZCQoHr9F4HfIV4hAwalf92Pk0H586q5kWtOdXY4KkRYt5QcM903tMv+ZzeCATg90qHhGdXbkycDr82UR7CYi6/MouaDoFLHCFYQDzxofhZUuBwUzrG91Jn0ndKb38PY6vIkTnuMjIG7cjM/h+zHqBpF6P6GeQsH6/fYiH3OjDluamxr4lZdbb09ZSGlRI4GQiO/S44OEiBB8KW/K4rp8cJ3mzqXkNi71I0JIKw+X0Y+exRbo78owAjjTzXirOBSOsE990HUgYBjFZjWwVBCOq65BSFemjIjA0CisMfEsy3uNrTXAXmzxM8KAIHvVTockqag891hs3Pt2QdidDGqf43xXDAy7wYm8AWYsEz+ulGbl3QFUiWp0u69QtvRnWPKUjGVKDX3jqqgAESvuJ9wGEMJFvxm75LqhC33cn9ztGi/8smgEcnuNJsbt71qDlnAuDsJ2djAeWdb3Tc8fzRHM07ImdIINddsxQn1gT0BW7sxBTlI8H98aCzzcxFi/L1H1Z9M0eHOe2hcTHHKGi0qBj2WHaXLCWkmDwVpJ0uRgA=
  file: generated-apks.zip
  overwrite: true
  skip_cleanup: true
  file_glob: true
  on:
    repo: adorsys/secure-key-storage