version: '2'
# Only  use this file for subsequent starts
services:   
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
    keycloak:
        # Keycloak image might be built prior to starting this file.
        image: sqrl/keycloak:1.0.0-SNAPSHOT
        links: 
            - mongo
        ports:
            - "8081:8080"
            - "9991:9990"
            - "8787:8787"
        volumes:
            # Startup script is stored in this directory.
            - ./volumes/idp-server/pre-deploy:/opt/jboss/keycloak/pre-deploy
            # Directory for the storage of keycloak generated configuration for sqrl-server
            - ./volumes/idp-server/data:/opt/jboss/keycloak/standalone/data
        environment:
            JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8787
            MONGO_HOST: mongo
            IDP_CONFIG_DIR: /opt/jboss/keycloak/standalone/data
        env_file:
            # For the productive environment, these properties muss be passed to the docker container -e
            - ./volumes/sqrl-server/sqrl-server.properties
        depends_on:
            - mongo
        entrypoint: /opt/jboss/keycloak/pre-deploy/docker-entrypoint.sh
        command: -b 0.0.0.0 -bmanagement 0.0.0.0 -c standalone-ha.xml
            